### ISSUE TITLE
新版本登录时报 MissingFieldException 错误

### ISSUE THREAD

**Issue by ShaoLongFei** [w4123/mirai-dice-release-noextra#2]
2023-03-07 12:59:42 E/main: kotlinx.serialization.MissingFieldException: Fields [display, product, device, board, brand, model, bootloader, fingerprint, bootId, procVersion, baseBand, version, simInfo, osType, macAddress, wifiBSSID, wifiSSID, imsiMd5, imei, apn] are required for type with serial name 'net.mamoe.mirai.utils.DeviceInfo', but they were missing
kotlinx.serialization.MissingFieldException: Fields [display, product, device, board, brand, model, bootloader, fingerprint, bootId, procVersion, baseBand, version, simInfo, osType, macAddress, wifiBSSID, wifiSSID, imsiMd5, imei, apn] are required for type with serial name 'net.mamoe.mirai.utils.DeviceInfo', but they were missing
	at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
	at net.mamoe.mirai.utils.DeviceInfo.<init>(DeviceInfo.kt:20)
	at net.mamoe.mirai.utils.DeviceInfo$$serializer.deserialize(DeviceInfo.kt:20)
	at net.mamoe.mirai.utils.DeviceInfo$$serializer.deserialize(DeviceInfo.kt:20)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:32)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:100)
	at net.mamoe.mirai.utils.DeviceInfo$Companion.from(DeviceInfo.kt:79)
	at net.mamoe.mirai.utils.LoginSolverKt$getFileBasedDeviceInfoSupplier$1.invoke(LoginSolver.kt:87)
	at net.mamoe.mirai.utils.LoginSolverKt$getFileBasedDeviceInfoSupplier$1.invoke(LoginSolver.kt:86)
	at net.mamoe.mirai.internal.network.components.SsoProcessorContextKt.createDeviceInfo(SsoProcessorContext.kt:47)
	at net.mamoe.mirai.internal.network.components.SsoProcessorContextImpl.<init>(SsoProcessorContext.kt:42)
	at net.mamoe.mirai.internal.QQAndroidBot.createBotLevelComponents(QQAndroidBot.kt:183)
	at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:151)
	at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:150)
	at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:38)
	at net.mamoe.mirai.internal.QQAndroidBot.getDefaultBotLevelComponents(QQAndroidBot.kt:150)
	at net.mamoe.mirai.internal.QQAndroidBot.createNetworkLevelComponents(QQAndroidBot.kt:236)
	at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:248)
	at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:241)
	at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelectorKt$KeepAliveNetworkHandlerSelector$1.createInstance(AbstractKeepAliveNetworkHandlerSelector.kt:218)
	at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.refreshInstance(AbstractKeepAliveNetworkHandlerSelector.kt:189)
	at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.getCurrentInstanceOrCreate(AbstractKeepAliveNetworkHandlerSelector.kt:57)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.getContext(SelectorNetworkHandler.kt:45)
	at net.mamoe.mirai.internal.QQAndroidBot.getComponents(QQAndroidBot.kt:148)
	at net.mamoe.mirai.internal.AbstractBot.login(AbstractBot.kt:135)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge$doStart$11$1.invokeSuspend(MiraiConsoleImplementationBridge.kt:267)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:224)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:276)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:152)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:151)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:47)

2023-03-07 12:59:42 I/Bot.1847809189: Bot cancelled: Job was cancelled
2023-03-07 12:59:42 E/Bot.1847809189: kotlinx.serialization.MissingFieldException: Fields [display, product, device, board, brand, model, bootloader, fingerprint, bootId, procVersion, baseBand, version, simInfo, osType, macAddress, wifiBSSID, wifiSSID, imsiMd5, imei, apn] are required for type with serial name 'net.mamoe.mirai.utils.DeviceInfo', but they were missing
kotlinx.serialization.MissingFieldException: Fields [display, product, device, board, brand, model, bootloader, fingerprint, bootId, procVersion, baseBand, version, simInfo, osType, macAddress, wifiBSSID, wifiSSID, imsiMd5, imei, apn] are required for type with serial name 'net.mamoe.mirai.utils.DeviceInfo', but they were missing
	at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
	at net.mamoe.mirai.utils.DeviceInfo.<init>(DeviceInfo.kt:20)
	at net.mamoe.mirai.utils.DeviceInfo$$serializer.deserialize(DeviceInfo.kt:20)
	at net.mamoe.mirai.utils.DeviceInfo$$serializer.deserialize(DeviceInfo.kt:20)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:32)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:100)
	at net.mamoe.mirai.utils.DeviceInfo$Companion.from(DeviceInfo.kt:79)
	at net.mamoe.mirai.utils.LoginSolverKt$getFileBasedDeviceInfoSupplier$1.invoke(LoginSolver.kt:87)
	at net.mamoe.mirai.utils.LoginSolverKt$getFileBasedDeviceInfoSupplier$1.invoke(LoginSolver.kt:86)
	at net.mamoe.mirai.internal.network.components.SsoProcessorContextKt.createDeviceInfo(SsoProcessorContext.kt:47)
	at net.mamoe.mirai.internal.network.components.SsoProcessorContextImpl.<init>(SsoProcessorContext.kt:42)
	at net.mamoe.mirai.internal.QQAndroidBot.createBotLevelComponents(QQAndroidBot.kt:183)
	at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:151)
	at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:150)
	at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:38)
	at net.mamoe.mirai.internal.QQAndroidBot.getDefaultBotLevelComponents(QQAndroidBot.kt:150)
	at net.mamoe.mirai.internal.QQAndroidBot.createNetworkLevelComponents(QQAndroidBot.kt:236)
	at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:248)
	at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:241)
	at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelectorKt$KeepAliveNetworkHandlerSelector$1.createInstance(AbstractKeepAliveNetworkHandlerSelector.kt:218)
	at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.refreshInstance(AbstractKeepAliveNetworkHandlerSelector.kt:189)
	at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.getCurrentInstanceOrCreate(AbstractKeepAliveNetworkHandlerSelector.kt:57)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.getContext(SelectorNetworkHandler.kt:45)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler$scope$2.invoke(SelectorNetworkHandler.kt:48)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler$scope$2.invoke(SelectorNetworkHandler.kt:47)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.getScope(SelectorNetworkHandler.kt:47)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.close(SelectorNetworkHandler.kt:82)
	at net.mamoe.mirai.internal.AbstractBot$coroutineContext$1$1.invoke(AbstractBot.kt:59)
	at net.mamoe.mirai.internal.AbstractBot$coroutineContext$1$1.invoke(AbstractBot.kt:55)
	at kotlinx.coroutines.InvokeOnCompletion.invoke(JobSupport.kt:1391)
	at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1519)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:906)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:863)
	at kotlinx.coroutines.JobSupport.cancelMakeCompleting(JobSupport.kt:696)
	at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:667)
	at kotlinx.coroutines.JobSupport.cancelInternal(JobSupport.kt:632)
	at kotlinx.coroutines.JobSupport.cancel(JobSupport.kt:617)
	at kotlinx.coroutines.Job$DefaultImpls.cancel$default(Job.kt:183)
	at net.mamoe.mirai.internal.AbstractBot.close(AbstractBot.kt:110)
	at net.mamoe.mirai.internal.QQAndroidBot.close(QQAndroidBot.kt:82)
	at net.mamoe.mirai.Bot.close(Bot.kt:178)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge$doStart$11$1.invokeSuspend(MiraiConsoleImplementationBridge.kt:269)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:224)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:276)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:152)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:151)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:47)

2023-03-07 12:59:42 I/main: mirai-console started successfully.

**Comment by ShaoLongFei** [comment]
可以删除自己指定的 device.json 再使用 https://github.com/cssxsh/mirai-device-generator 插件解决
